apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      name: forwarder
  template:
    metadata:
      labels:
        name: forwarder
    spec:
      serviceAccountName: forwarder
      containers:
        - name: forwarder
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - forwarder
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "forwarder"
