kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: forwarder
subjects:
- kind: ServiceAccount
  name: forwarder
roleRef:
  kind: Role
  name: forwarder
  apiGroup: rbac.authorization.k8s.io
